name: Deploy to InfinityFree via FTP

on:
  push:
    branches:
      - main  

jobs:
  web-deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
    - name: Lay code moi nhat
      uses: actions/checkout@v3

    - name: Dong bo file qua FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /htdocs/wp-content/themes/my-esport-theme/
